### ISSUE TITLE
libunistring missing for git

### ISSUE THREAD

**Issue by keaton-dev** [ProcursusTeam/Procursus#11]
When using git without installing libunistring manually you will receive this error:
`dyld: dependent dylib '/usr/lib/libunistring.2.dylib' not found for '/usr/lib/libidn2.0.dylib', tried but didn't find: '/usr/lib/libunistring.2.dylib' '/usr/local/lib/libunistring.2.dylib' '/usr/lib/libunistring.2.dylib'`

**Comment by Diatrus** [comment]
Appreciated. I’ll push an update when I get home.

**Comment by Diatrus** [comment]
The problem stems from a seemingly late-night addition where the libidn2 control file has `Requires:` instead of `Depends:`.
