### ISSUE TITLE
PAM stuff might not working as expected

### ISSUE THREAD

**Issue by Torrekie** [ProcursusTeam/Procursus#1122]
I have compiled a `su` from `shell-cmds`, and it cannot call `pam_start`
```
iPhone:/ root# su
su: pam_start: System error
```
After checking the console log, I found this one
```
in openpam_load_module(): no pam_rootok.so found
```
But I'm sure that there is a `pam_rootok.so` lying in /usr/lib/pam, after checking openpam's source code, I found this part might be a bug
```
iPhone:/openpam-20190224/lib/libpam root# cat openpam_constants.c
...
const char *openpam_module_path[] = {
#ifdef OPENPAM_MODULES_DIRECTORY
        OPENPAM_MODULES_DIRECTORY,
#else
        "/usr/lib",
        "/usr/local/lib",
#endif
        NULL
};
```
there was no `OPENPAM_MODULES_DIRECTORY` defined entire time, causing modules in `/usr/lib/pam` not being searched by libpam. In fact there is a macro `OPENPAM_MODULES_DIR` refers to modules directory which defined in `config.h`, changing `OPENPAM_MODULES_DIRECTORY` to `OPENPAM_MODULES_DIR` can fix that problem.

**Comment by CRKatri** [comment]
`OPENPAM_MODULES_DIRECTORY` gets replaced by `OPENPAM_MODULES_DIR` in the patch [softcode_paths.patch](build_patch/openpam/softcode_paths.patch). Did you build the openpam manually, instead of with Procursus?

**Comment by Torrekie** [comment]
> 

oh, I didn't check the updates, this patch was not included when I clone this repo few months ago, my bad
