### ISSUE TITLE
Mirror Sync in Progress Issue

### ISSUE THREAD

**Issue by decidedlygray** [ProcursusTeam/Procursus#1140]
Hello,

While using a third-party tool, the install script fails when attempting to retrieve a package (`system-cmds`) from your repository. The error message is:

```
Get:42 https://apt.procurs.us iphoneos-arm64/1700/main iphoneos-arm system-cmds iphoneos-arm 854.40.2-13 [211 kB]
Err:42 https://apt.procurs.us iphoneos-arm64/1700/main iphoneos-arm system-cmds iphoneos-arm 854.40.2-13
  File has unexpected size (211372 != 211400). Mirror sync in progress? [IP: 104.21.46.121 443]
  Hashes of expected file:
   - SHA512:7fa1be40cab303208ed686474a737287a6eb4d5b6381f2638bf11267382f572603df371904ba596ddc9de3bbc09edda786f13b2b18a97bd9d5db30d38f50b036
   - SHA256:2bbfc1a52344e58b9426dad29aac0fb16d89e30e0747e3a410eee0562a33918a
   - SHA1:4c13ed783158da2ac2afa532d242e05aa1afeb7d [weak]
   - MD5Sum:65b392f64aad4b4ba0d7aaa82bfef8b3 [weak]
   - Filesize:211400 [weak]
```
In case it was some kind of syncronization issue I waited a few days and tried again, but it appears the issue hasn't gone away. 

Full output has also been posted here: https://github.com/coolstar/Odyssey-bootstrap/issues/43

I was wondering if you are aware of any workarounds for this?

Thank you for your time,
DG

**Comment by CRKatri** [comment]
Hmm, this was fixed a couple weeks ago. The actual issue was due to a bad hash being cached, but the cache has been reset since, so I'm not quite sure what is causing this.

**Comment by decidedlygray** [comment]
My thinking is it is with something related to the install script, not with Procursus. After the install fails I can do an `apt update && apt install system-cmds` and it installs fine. I will follow up when I confirm and close this ticket out

**Comment by TheRealKeto** [comment]
The output you left on the linked issue directly tells you to try using the ``--fix-missing`` flag along with the APT command. This might need a script fix, which can be provided should the flag fix your issue.

**Comment by decidedlygray** [comment]
Interesting - I set up to test `--fix-missing` today and the issue seems to have been resolved without the flag. Thank you for your help! Closing
