### ISSUE TITLE
`ld: library not found for -liosexec` error on iOS 13.7

### ISSUE THREAD

**Issue by arinc9** [ProcursusTeam/Procursus#1232]
I'm trying to build a go project (https://github.com/dsnet/udptunnel). It fails with this:
```
$ /usr/lib/go-1.18/bin/go build
# github.com/dsnet/udptunnel
/usr/lib/go-1.18/pkg/tool/ios_arm64/link: running cc failed: exit status 1
ld: library not found for -liosexec
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

It will print the same output on go-1.16, go-1.17. It compiles fine on go-1.15

With go-1.16 and newer, go was made to be compiled with libiosexec as a dependency:
https://github.com/ProcursusTeam/Procursus/commits/11a3a9a0cc5e59af5337e2e35c33d9752ea1109b/build_patch/golang/libiosexec.diff

**Comment by TheRealKeto** [comment]
Unsure why you have a problem; I was able to compile it just fine from a fresh install, though I'm not sure about its acutual functionality

```zsh
➜ sudo apt install golang-go
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  golang-1.18-go golang-1.18-src libiosexec-dev
The following NEW packages will be installed:
  golang-1.18-go golang-1.18-src golang-go libiosexec-dev
0 upgraded, 4 newly installed, 0 to remove and 1 not upgraded.
Need to get 81.0 MB of archives.
After this operation, 495 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://apt.procurs.us iphoneos-arm64/1500/main iphoneos-arm libiosexec-dev iphoneos-arm 1.0.20~1.1-alpha1 [6564 B]
Get:2 https://apt.procurs.us iphoneos-arm64/1500/main iphoneos-arm golang-1.18-src iphoneos-arm 1.18 [16.2 MB]
Get:3 https://apt.procurs.us iphoneos-arm64/1500/main iphoneos-arm golang-1.18-go iphoneos-arm 1.18 [64.7 MB]
Get:4 https://apt.procurs.us iphoneos-arm64/1500/main iphoneos-arm golang-go all 1.18 [61.8 kB]
Fetched 81.0 MB in 36s (2224 kB/s)
Selecting previously unselected package libiosexec-dev.
(Reading database ... 29046 files and directories currently installed.)
Preparing to unpack .../libiosexec-dev_1.0.20~1.1-alpha1_iphoneos-arm.deb ...
Unpacking libiosexec-dev (1.0.20~1.1-alpha1) ...
Selecting previously unselected package golang-1.18-src.
Preparing to unpack .../golang-1.18-src_1.18_iphoneos-arm.deb ...
Unpacking golang-1.18-src (1.18) ...
Selecting previously unselected package golang-1.18-go.
Preparing to unpack .../golang-1.18-go_1.18_iphoneos-arm.deb ...
Unpacking golang-1.18-go (1.18) ...
Selecting previously unselected package golang-go.
Preparing to unpack .../golang-go_1.18_all.deb ...
Unpacking golang-go (1.18) ...
Setting up libiosexec-dev (1.0.20~1.1-alpha1) ...
Setting up golang-1.18-src (1.18) ...
Setting up golang-1.18-go (1.18) ...
Setting up golang-go (1.18) ...
➜ git clone --recursive "https://github.com/dsnet/udptunnel.git" udp && cd udp
Cloning into 'udp'...
remote: Enumerating objects: 135, done.
Receiving objects: 100% (135/135), 41.69 KiB | 1.39 MiB/s, done.
remote: Total 135 (delta 0), reused 0 (delta 0), pack-reused 135
Resolving deltas: 100% (84/84), done.
➜ /usr/lib/go-1.18/bin/go build
go: downloading github.com/dsnet/golib/jsonfmt v0.0.0-20190531212259-571cdbcff553
go: downloading github.com/dsnet/golib/unitconv v0.0.0-20190531212259-571cdbcff553
go: downloading github.com/songgao/water v0.0.0-20190402020555-6ad6edefb15c
➜ ./udptunnel
Usage:
        ./udptunnel CONFIG_PATH
```

**Comment by arinc9** [comment]
I have no idea. I can see the library at `/usr/lib`:
```
$ ls -al /usr/lib/libiosexec.*
-rw-r--r-- 1 root 81824 Oct 14  2021 /usr/lib/libiosexec.1.dylib
-rw-r--r-- 1 root 10704 Oct 14  2021 /usr/lib/libiosexec.a
lrwxr-xr-x 1 root    18 Oct 14  2021 /usr/lib/libiosexec.dylib -> libiosexec.1.dylib
```
Anyway, it must be something from my side as it works fine in your case. I'll try again after a rootfs restore.

A few off topic questions:
How exactly do you define the procursus repo on apt sources list? I currently have this hacky way:
`deb https://apt.procurs.us/ dists/iphoneos-arm64/1800/main/binary-iphoneos-arm/`
And how do you get around the `Release is not signed` warning?

At which directory do you compile this? I use odysseyra1n and I'm yet to figure out a directory where I don't need to give entitlements to the binary using `ldid`.

**Comment by CRKatri** [comment]
Odysseyra1n will give a sources list automatically, also there is no 1800 dist available.

Go should be adhoc signing automatically, just make sure you are not in /var, anything under /var will be killed due to sandboxing.

**Comment by CRKatri** [comment]
Also, here is a valid .list entry `deb https://apt.procurs.us/ iphoneos-arm64/1700 main`

**Comment by arinc9** [comment]
I accidentally removed the sources list (oops). Thanks for the valid entry. The unsigned issue is automatically resolved with this.

Do you mean 1800 dist is a placeholder? Because I used to feed apt [using it](https://apt.procurs.us/dists/iphoneos-arm64/1800/).

> Go should be adhoc signing automatically, just make sure you are not in /var, anything under /var will be killed due to sandboxing.

`/tmp` has the same behaviour too. It works on `/test` directory that I just created, thanks!

**Comment by CRKatri** [comment]
> I accidentally removed the sources list (oops). Thanks for the valid entry. The unsigned issue is automatically resolved with this.
> 
> Do you mean 1800 dist is a placeholder? Because I used to feed apt [using it](https://apt.procurs.us/dists/iphoneos-arm64/1800/).

It's a symlink to 1700 (iOS 14), 1800 is for iOS 15. The 1800 dist won't actually be used because iOS 15 will be rootless and have a different setup.

> > Go should be adhoc signing automatically, just make sure you are not in /var, anything under /var will be killed due to sandboxing.
> 
> `/tmp` has the same behaviour too. It works on `/test` directory that I just created, thanks!

`/tmp` is a symlink under `/var`

**Comment by CRKatri** [comment]
Are you still having issues linking?

**Comment by arinc9** [comment]
I just tried it again after a rootfs restore. Reinstalled golang-go and the issue is still there. This might be an issue for iOS 13 only.

**Comment by CRKatri** [comment]
Can you try running `sudo sed -i 's|-liosexec|/usr/lib/libiosexec.dylib|' /usr/lib/go-1.18/src/runtime/cgo/cgo.go`

**Comment by arinc9** [comment]
It compiled fine with this!

**Comment by arinc9** [comment]
Do you plan to address this on the repository? Should I close the issue?

By the way, I had the same issue on go-1.17. `s|-liosexec|/usr/lib/libiosexec.dylib|` at `/usr/lib/go-1.17/src/runtime/cgo/cgo.go` solved it. go-1.16 is probably affected too.

**Comment by CRKatri** [comment]
Yes, I'm trying to identify the actual issue, because it works for Keto on iOS 12, so I think it may be an issue with `ld64` on iOS 13

**Comment by badger200** [comment]
> Yes, I'm trying to identify the actual issue, because it works for Keto on iOS 12, so I think it may be an issue with `ld64` on iOS 13

In my experience with clang 10, 11, 12, 13, and 14 on iOS, using -isysroot is usually the culprit. Once that’s used, clang Driver or Frontend/ToolChains/Darwin.cop source automatically makes all -L /usr/lib and -lwhatever get appended to $SDK/, making it impossible to utilize libraries like /usr/lib/libiosexec.dylib. Your workaround of using the full path circumvents this, but I always try to avoid invoking -isysroot in the first place. I’ve ended up making a handful of small edits to stock Clang release source (releases.llvm.org) to fix these all for good.

For us iOS jailbroken developers, it’s important that we get /usr/lib added to our library path, as Apple has recently changed to apparently make all user stuff go into /usr/local/lib, so any -lwhatever library commands never check inside /usr/lib at all.

I also had to edit the Frontend/Driver code InitHeaderSearch.cpp (they moved it between clang-13 and clang-14) to add the normal $SDK/usr/lib, $SDK/usr/include, and Frameworks did $SDK/System/Library/Frameworks.

I’m using the Procursus ld64-609-2 with my custom compiled (but nearly-stock) clangs 12/13/14/15git on iOS 14.4, A12X iPad Pro, unc0ver 8.0.2, obviously not a “stock” jailbreak setup.

One other key fix I believe in clang/lib/Driver/ToolChains/Darwin.cpp is to change their arbitrary assumption that -arch arm64 automatically implies Apple Silicon M1/OSX, I simply change it to default to “IOS” since I don’t even have a Mac lol. That makes a huge difference. I literally almost never use -isysroot and sometimes I even remove it from sources that otherwise fail to compile on device.
