### ISSUE TITLE
Please stop deleting /usr/share/info

### ISSUE THREAD

**Issue by asdfugil** [ProcursusTeam/Procursus#1235]
We have `info(1)`, why delete /usr/share/info? It's not like HTML in /usr/share/doc where there is no good way to read it.

**Comment by CRKatri** [comment]
Because they are dumb. It is a redundant format created because GNU because they didn't want to write manpages. But we can put them in, I dislike them but we can distribute them, I don't really care. But if you do, debianize texinfo first.

**Comment by asdfugil** [comment]
ok this is actually dumb
```
mobile@iPad [0]:~$ info bash
info: Terminal type 'xterm-256color' is not smart enough to run Info
mobile@iPad [1]:~$ TERM=xterm info bash # display a man page
mobile@iPad [0]:~$
```
