### ISSUE TITLE
disked-cmds is causing problems

### ISSUE THREAD

**Issue by dxcool222** [ProcursusTeam/Procursus#1320]
if I Update disked-cmds in Sileo on my iPad mini 4 it will cause the device not to boot and get stuck on the palera1n logo I have to format my device just to get it to work please look into this on 15.7.1 with palera1n

**Comment by CRKatri** [comment]
This has been fixed in c91ded9, however because we do not have an official iOS 15 repo, please contact whoever built the package you are using and ask them to update.
