### ISSUE TITLE
`shshd` and `essential` packages on the apt repo are out-of-date 

### ISSUE THREAD

**Issue by L1ghtmann** [ProcursusTeam/Procursus#1333]
On the repo as of 12/11:
- `shshd` v1.1.1.1 -- which is marked as `Essential`
- `essential` v0-5 -- which has `shshd` as a dependency 

Both of these characteristics were changed by [02fc04e](https://github.com/ProcursusTeam/Procursus/commit/02fc04e5eaa2c829a96afbab389a95e9a184d04a) back in June, but the packages currently available do not reflect this. If they could be updated, that would be super helpful. Thanks!

**Comment by Cryptiiiic** [comment]
You forgot to close this @L1ghtmann

**Comment by L1ghtmann** [comment]
@Cryptiiiic nope, this was left open intentionally as the packages available appear to still lack the aforementioned changes.
