### ISSUE TITLE
libpython3.9.dylib uses _mkfifoat (Symbol not found)

### ISSUE THREAD

**Issue by anoane** [ProcursusTeam/Procursus#1396]
Installed:

libpython3.9_3.9.9-1_iphoneos-arm64.deb
python3.9_3.9.9-1_iphoneos-arm64.deb
python3_3.9.9-1_iphoneos-arm64.deb
python3-wcwidth_0.2.5_iphoneos-arm64.deb
python3-binwalk_2.3.3_all.deb
python3-pygments_2.11.2_all.deb
python3-unicorn_2.0.1.post1_iphoneos-arm64.deb
python3-libxml2_2.9.12_iphoneos-arm64.deb
python3-prompt-toolkit_3.0.25-1_all.deb
python3-pyaes_1.6.1_all.deb

From:

https://apt.procurs.us/pool/main/iphoneos-arm64-rootless/1900/python3/

Trying:

root# python -m ensurepip

dyld[8395]: Symbol not found: _mkfifoat
  Referenced from: /private/preboot/jb/usr/lib/libpython3.9.dylib
  Expected in: /usr/lib/libSystem.B.dylib
zsh: abort      python -m ensurepip

**Comment by CRKatri** [comment]
What iOS version? What jailbreak?

**Comment by anoane** [comment]
https://github.com/pinauten/Fugu15
it's a iPhone 11 on 15.4.1

**Comment by CRKatri** [comment]
You are using builds for iOS 16. Switch to the `1800` repo.
