### ISSUE TITLE
system-cmds breaks passwd / PAM

### ISSUE THREAD

**Issue by anoane** [ProcursusTeam/Procursus#1397]
After installing this package:

https://apt.procurs.us/pool/main/iphoneos-arm64-rootless/1900/system-cmds/system-cmds_950-2_iphoneos-arm64.deb

passwd stops working

**Comment by CRKatri** [comment]
Do you have an error message? Or any steps to reproduce? We did lots of testing before pushing that update and it worked great for us.

**Comment by anoane** [comment]
I'm using Fugu
https://github.com/pinauten/Fugu15
it's a iPhone 11 on 15.4.1

so before installing the package, if i do "passwd", i get "New password:"
after installing the package if I do "passwd", i get instead some "Generic Error" or something like that

**Comment by CRKatri** [comment]
Please make sure to use the iOS 15 (`1800`) repo, there is a difference between the builds.

**Comment by anoane** [comment]
sorry, tried the 1800 and at least on Fugu 15 I get the same error:
passwd: Error in service module

**Comment by CRKatri** [comment]
Please reinstall `system-cmds`, `libpam2` and `libpam-modules`.

**Comment by Tokarak** [comment]
I had a broken `login` tool (always returned code 1), which I fixed by reinstalling `system-cmds`. Could it be related?

**Comment by Cryptiiiic** [comment]
you probably had uar repo's login at one point

**Comment by anoane** [comment]
> Please reinstall `system-cmds`, `libpam2` and `libpam-modules`.

yep, that worked
dpkg --force-all -i libpam2*.deb libpam-modules*.deb system-cmds*.deb shell-cmds*.deb
did the trick
