### ISSUE TITLE
Cannot install sqlite 3

### ISSUE THREAD

**Issue by tdzard94** [ProcursusTeam/Procursus#1442]
Today i cannot install sqlite3 from your repo
Please fix

![Screen Shot 2024-06-04 at 18 26 51](https://github.com/ProcursusTeam/Procursus/assets/13480279/85c58181-36d1-4b58-a465-237362c27e13)

This is error log
Thankyout

**Comment by asdfugil** [comment]
We believe that this issue has now been fixed. Please try again.

**Comment by tdzard94** [comment]
it's worked. Thankyou
