### ISSUE TITLE
[ REQUEST ] XMake / G++ for compiling c++

### ISSUE THREAD

**Issue by DwifteJB** [ProcursusTeam/Procursus#173]
https://xmake.io/ is a tool for compiling tool based on lua. I would love if you ported this (most of the dependencies are already in procursus).

G++ is like xmake but more complicated.

Would love if you ported it!

**Comment by CRKatri** [comment]
We already have clang, no need to add gcc.

**Comment by DwifteJB** [comment]
Yes I noticed, forgot to close sorry!
