### ISSUE TITLE
Package Request: FFmpeg

### ISSUE THREAD

**Issue by Randomblock1** [ProcursusTeam/Procursus#207]
I’d like to get FFmpeg added. It has a fair amount of dependencies, but MCApollo has already done pretty much all of the work at https://github.com/MCApollo/repo. All you need to do is convert their build system to Procursus’ and it should work.

I _might_ be able to do this myself, but I haven’t built from Procursus before and I have to run MacOS inside a VM.

**Comment by CRKatri** [comment]
This is already a WIP, we're going through the deps (albeit fairly slowly) on the ffmpeg branch. If you would like to help with this contact me on [Hayden's discord](https://diatr.us/discord), I'll be able to help you there, macOS is not required, most stuff builds fine on Linux.

**Comment by 1Conan** [comment]
> I _might_ be able to do this myself, but I haven’t built from Procursus before and I have to run MacOS inside a VM.

You don't need macos save for a few packages like nodejs and golang. I personally use linux to build stuff. (Check the readme)

**Comment by Randomblock1** [comment]
I don't know how I missed an _entire branch_ named ffmpeg, but thanks, I'll take a look at it. It also took a little too long for me to figure out cctools, so I went ahead and made a [pull request](../pull/209) with more detailed Linux instructions.
Guess I'll keep this issue open until ffmpeg is done.

**Comment by spermlord** [comment]
> > I _might_ be able to do this myself, but I haven’t built from Procursus before and I have to run MacOS inside a VM.
> 
> You don't need macos save for a few packages like nodejs and golang. I personally use linux to build stuff. (Check the readme)

Can you please tell me how to build nodejs on WSL2? I typed `make nodejs-package` but it said I need a macOS to build: `nodejs building only supported on macOS`. Thank you
