### ISSUE TITLE
How to compile a C++ program with clang from repo?

### ISSUE THREAD

**Issue by Officeyutong** [ProcursusTeam/Procursus#208]
I have installed clang-10, libclang-common-10-dev, libclang-cpp10, libc++-10-dev and libc++-dev from the Procursus, but when I used clang-10 to compile a C++ program, it gives me the following errors:
```
YTs-iPad-Pro:~ root# cat test.cpp
#include <iostream>

using namespace std;

int main(){
        cout << "test" << endl;
        return 0;
}
YTs-iPad-Pro:~ root# clang-10 test.cpp
In file included from test.cpp:1:
In file included from /usr/bin/../include/c++/v1/iostream:37:
In file included from /usr/bin/../include/c++/v1/ios:214:
In file included from /usr/bin/../include/c++/v1/iosfwd:95:
/usr/bin/../include/c++/v1/wchar.h:118:15: fatal error: 'wchar.h' file not found
#include_next <wchar.h>
              ^~~~~~~~~
1 error generated.
YTs-iPad-Pro:~ root# 
```

Does this mean that I have forgot to install some packages(such as a certain type of Standard C Libraries) ? or C++ programs are not supported now?

OS: iPadOS 13.5.1
Jailbreak: Odyssey 1.2
Device: iPad Pro 2020 11-inch
Package manager: Sileo

**Comment by Diatrus** [comment]
Place an iPhoneOS sdk in /usr/share/SDKs, restart your terminal, and try again.

**Comment by CRKatri** [comment]
Also make sure `build-essential` is installed

**Comment by Officeyutong** [comment]
> Place an iPhoneOS sdk in /usr/share/SDKs, restart your terminal, and try again.

I copied the iPhoneOS sdk from the XCode , then another error occured

```

**Comment by Diatrus** [comment]
You need c++ headers from the Xcode toolchain.

**Comment by CRKatri** [comment]
Besides the weird stuff that happened with `/var` that needs to be fixed you should also be running `clang++` to compile.

**Comment by Officeyutong** [comment]
> You need c++ headers from the Xcode toolchain, or install libc++-dev
> 
> EDIT: I just noticed the error was from `/var/include/wchar.h`, why is that there? lol

I solved my problem by removing /var/include, thanks XD
