### ISSUE TITLE
Package request: toybox and/or busybox

### ISSUE THREAD

**Issue by asdfugil** [ProcursusTeam/Procursus#212]
Hello, could you add toybox or busybox? I need them to set up different small environments in some workflows. Thank you very much.

**Comment by Diatrus** [comment]
Can you link me to the website for toy or busybox? Not sure what exactly you’re referencing.

**Comment by asdfugil** [comment]
busybox -> https://busybox.net/ 
toybox -> https://landley.net/toybox/about.html

**Comment by CRKatri** [comment]
I see no need for this on iOS, we have all the tools in Busybox already on the repo to my knowledge. If you don't want to bootstrap then binpack, that comes on an unbootstrapped checkra1n, has lots of the standard tools, you can also use [binbag](http://newosxbook.com/tools/iOSBinaries.html) if you need one binary
