### ISSUE TITLE
tmux appears broken

### ISSUE THREAD

**Issue by deatondg** [ProcursusTeam/Procursus#226]
I cannot get tmux to work. Running `tmux` on my iPad Pro 4 results in
```
[server exited unexpectedly]
                            %                                                                                                                                                              Daviss-iPad:~ mobile% 
/1;2c_
```
I think this also used to work, but I don’t remember when. Let me know if there’s anything I can do to help debug.

Sidenote: thanks for fixing my last issue in less than 10 min. You’re incredible.

**Comment by Diatrus** [comment]
Fixed in 0e51f487c408e9cc7f25a81c15420ca1e5533bb8

To the sidenote: no problem at all.
