### ISSUE TITLE
Package requests

### ISSUE THREAD

**Issue by demhademha** [ProcursusTeam/Procursus#25]
Hi, could you please add support for clang (with arm64e support) aswell as libswift and the swift toolchain?
Thank you

**Comment by Diatrus** [comment]
These were added in 91f7343d795e41463e8862ba90d228c9557bea7c. Swift does need some work, but I'm not neglecting it.

**Comment by demhademha** [comment]
Thank you 
But it still seems that theos isn't working

**Comment by Diatrus** [comment]
That’s extremely undetailed, but I can guarantee it’s working for me and others.

**Comment by demhademha** [comment]
Ok, when compiling, i get the following: 
ahmeds-iPad:/var/github/b root# make clean package
==> Cleaning…
> Making all for tool b…
==> Compiling main.m (armv7)…
==> Compiling main.m (arm64)…
==> Linking tool b (arm64)…
==> Linking tool b (armv7)…
==> Merging tool b…
==> Signing b…
> Making stage for tool b…
bash: /var/github/b/.theos/_ /DEBIAN/control: No such file or directory
make: *** [/var/root/theos/makefiles/package/deb.mk:51: /var/github/b/.theos/_ /DEBIAN/control] Error 1
ahmeds-iPad:/var/github/b root
Main file contains:
#include <stdio.h>

int main(int argc, char *argv[], char *envp[]) {
	printf("Hello world!\n");
	return 0;
}


Control file contains:
 
Package: b
Name: b
Version: 0.0.1
Architecture: iphoneos-arm
Description: An awesome tool of some sort!!
Maintainer: b
Author: b
Section: System
Tag: role::hacker


the same package works fine on checkra1n
any help would be appreciated

**Comment by CRKatri** [comment]
Switch to the `next` branch of theos

- Cameron Katri

________________________________

**Comment by demhademha** [comment]
Thank you very much, but what about this
make install
==> Installing…
su: illegal option -- c
usage: su [-dflm] [login [shell arguments]]
make: *** [/var/root/theos/makefiles/install/deb_local.mk:2: internal-install] Error 1
:
Looks like an issue with sudo / fakeroot 
However, the deb does compile with the next branch of theos

**Comment by CRKatri** [comment]
Please make sure you are running and installed theos as mobile

- Cameron Katri

________________________________

**Comment by Diatrus** [comment]
@CRKatri is incorrect, it’s an issue with how theos invokes su, it isn’t compatible with BSD su. Report to theos that they’re incompatible with FreeBSD su on Procursus. I’ll likely fix it and create a pull request later.

**Comment by keaton-dev** [comment]
A work around for the install issue is to change the line `exec su -c "$@"` to `exec bash -c "$@"` in `(theos_dir)/bin/install.exec`.

[This](https://github.com/theos/theos/pull/516) pull request mentions the issue you are having @demhademha.
