### ISSUE TITLE
Package Requests: librtlsdr, libnfc, dump1090

### ISSUE THREAD

**Issue by JQ555888** [ProcursusTeam/Procursus#285]
Basically a bunch of utilities that do dope things by communicating with the device using its USB interface (with the iPhone being USB host).

None of them has ever been previously available to iOS due to libusb not being available (or at least publicly) before this year. Now that I've tested libusb to be working with both the CCK (via lightning and external power supply) as well as Type-C extension docks (via USB C), these utilities should be able to work just fine.

https://github.com/antirez/dump1090
https://github.com/librtlsdr/librtlsdr
https://github.com/nfc-tools/libnfc

**Comment by JQ555888** [comment]
Quick update: got bored and tried to compile librtlsdr and dump1090 both linking against libusb

And... surprise surprise with few modifications EVERYTHING WORKS AS EXPECTED

To make things easier I've compiled librtlsdr and packaged it into a deb and modified its control file so it's consistent with debian package names in its "Provides" list of packages. I've uploaded the said [test deb](https://cdn.discordapp.com/attachments/781041045760770049/794763177781887036/librtlsdr_0.8.0_iphoneos-arm.deb) into the discord channel. 

Here's proof that [it works](https://cdn.discordapp.com/attachments/781041045760770049/794766079708495882/Screen_Shot_2021-01-02_at_3.10.31_AM.png)

**Comment by JQ555888** [comment]
https://cdn.discordapp.com/attachments/781041045760770049/794766079708495882/Screen_Shot_2021-01-02_at_3.10.31_AM.png

**Comment by JQ555888** [comment]
Update:

librtlsdr and dump1090 works perfectly, been running a minimal ADSB server for flightradar24 & flightaware several days on my iPad with a third party CCK connected to a DVB-T stick. Not a lot needs to be changed - as long as you're able to compile it it will work. Expect reliability to be somewhat similar to an RPi.

libnfc on the other hand was painful as it relies on the old libusb-0.1 rather than libusb-1.0. Had to manually compile libusb-compat as libusb-0.1 doesn't properly support Darwin's aarch64 variant arm64 by default. When you finally sort out libusb-compat you'll realise it still won't compile, probably due to you the fact you aren't supposed to be doing it on Darwin with an architecture other than x86 as it's giving an error on a missing argument. Anyways, I gave up until someone else's managed to make it work reliably.

The entire reasoning behind wanting to compile libnfc is for it to work with PN532 modules so you could theoretically copy cards on the fly without using your device's built-in NFC. But at this point it's certainly not worth the trouble. I'd recommend buying an RPi if you intend to do that sort of things.

**Comment by Diatrus** [comment]
@JQ555888 I would much appreciate you PR-ing the finished tools and libraries. I can work on libusb-compat myself.
