### ISSUE TITLE
glibtoolize in GNU Libtool appears to be broken

### ISSUE THREAD

**Issue by JQ555888** [ProcursusTeam/Procursus#291]
Trying to compile various projects on device that utilize GNU Libtool often results in the following error:
"glibtoolize:   error: $pkgauxdir is not a directory: '/usr/share/libtool/build-aux'"

Upon further investigation I could see the program is actually trying to do "glibtoolize --copy --force" which for some reason glibtoolize is consistently giving an error. It seems to have something to do with an env variable error in the on-device build system but I couldn't be certain as I'm not exactly familiar with it. This is kind of annoying as cross-compiling sometimes isn't easily possible with certain packages and so on-device offers a better route.

This error can be easily triggered by running "autoreconf -vis" which exists in a fair amount of projects as it also depends on a working glibtoolize. Please correct me if I made an error somewhere but I hope this issue can be fixed :)

**Comment by Diatrus** [comment]
The error is indeed my fault, I'll fix shortly.

**Comment by JQ555888** [comment]
Ahh after a bit of fiddling around with the libtool package I could see what went wrong - basically the entire directory /usr/share/libtool/ is missing from the original package. In case anyone's looking for a quick fix here's the deb https://cdn.discordapp.com/attachments/763074782220517467/795147082838573086/libtool_2.4.6-9_iphoneos-arm.deb. 

Essentially I unsplit libltdl7 from libtool and put everything under one package - I'm 80% sure this is not the proper way to do it as debian seems to have done it differently - but then again at least everything works now.

Thank you Diatrus for the quick reply! :D

**Comment by CRKatri** [comment]
A fix actually already got pushed for this with 6e00546

**Comment by Diatrus** [comment]
@JQ555888 I've pushed updates to reorganize where the files are in each package. You may get errors upgrading if you keep libltdl-dev installed right now, but reinstalling fresh will work fine.

**Comment by JQ555888** [comment]
> A fix actually already got pushed for this with [6e00546](https://github.com/ProcursusTeam/Procursus/commit/6e00546343d47af1c45d789b21c64b91b4770a79)

Ah nice!! Man that was seriously fast :P 

Thank you guys so much!!

**Comment by JQ555888** [comment]
> @JQ555888 I've pushed updates to reorganize where the files are in each package. You may get errors upgrading if you keep libltdl-dev installed right now, but reinstalling fresh will work fine.

Gotcha! Cheers
