### ISSUE TITLE
`man` crashes until zstd is manually installed.

### ISSUE THREAD

**Issue by deatondg** [ProcursusTeam/Procursus#292]
On my system, running `man` results in
```
man: can't execute zstd: No such file or directory
```
until zstd is manually installed. 

I am not sure what is up with this: I just checked the build_info/man-db.control file, and it has a zstd requirement, so I’m not really sure why zstd doesn’t install with man-db.

**Comment by CRKatri** [comment]
We added the dependency to man-db, but an updated deb has not been pushed to the apt repository, sorry for the inconvenience, it's been annoying me as well.

**Comment by Diatrus** [comment]
This will stay open until I update the deb.
