### ISSUE TITLE
Package requests

### ISSUE THREAD

**Issue by demhademha** [ProcursusTeam/Procursus#37]
Hi, could you please add Pinentry and partial-zip-browser? 
thanks

**Comment by Diatrus** [comment]
I'll get to work on it. Curious why you're requesting Pinentry? :)

**Comment by demhademha** [comment]
How else am I to make gpg keys :p

**Comment by Diatrus** [comment]
Closed in https://github.com/ProcursusTeam/Procursus/commit/bcb7184c30542294c46594bd4654f76cfe0216cf and https://github.com/ProcursusTeam/Procursus/commit/5a1d844e286e1a49064d67a4264994f3a7b50aac

**Comment by demhademha** [comment]
Thank you buddy
