### ISSUE TITLE
Python wheels are unable to be created with clang when installing packages from a source tree.

### ISSUE THREAD

**Issue by TheRealKeto** [ProcursusTeam/Procursus#417]
**Description**
``clang`` is unable to build wheels when installing Python packages from a source tree. This happens on ``python3.8`` and ``python3.9``, with tracebacks showing that certain files from ``clang`` are missing, despite them actually existing. This leads to packages being unable to be installed since they require wheels to be created.

**How to reproduce**
You'll need to install a the following packages:
- ``python3`` (This can be either Python 3.8 or 3.9)
- ``clang``
- ``libcrypt-dev``

You'll also need an SDK in ``/usr/share/SDKs``. Once you have these requirements, attempt to install packages from a source tree, like ``multidict`` or ``discord.py``.

Installing these packages from a source tree will not work, since [PEP517](https://www.python.org/dev/peps/pep-0517/) is a thing. However, this can be bypassed by adding ``--no-use-pep517`` flag before installing. Even after doing this, [the following traceback is returned](https://mystb.in/DealtimeMustangCreates).

The traceback shows that the file, ``stdio.h`` is missing from ``clang``. Checking on ``/usr/include/c++/v1/`` shows that ``stdio.h`` exists. Installing other packages, such as ``discord.py`` from a source tree also throws an error similar to the one provided above.

**Device Info**
This was done on an ``iPod7,1`` running iOS 12.4.1 using Chimera 1.6.2, in a Python virtual environment created with Python 3.9.

**Comment by marijuanARM** [comment]
Thank you, README dev.

**Comment by TheRealKeto** [comment]
**Update**: I forgot to mention the fact that the SDK I used alongside ``clang`` and ``build-essential`` was patched, coming straight from [theos/sdks](https://github.com/theos/sdks). Previously, SDKs provided by Theos have worked, but I have no way of testing whether these SDKs cause problems now, since I don't have access to a "normal" SDK.

**Comment by TheRealKeto** [comment]
**2nd Update**: After another contributor to Procursus provided a normal SDK to me (with its target version being iOS 14.3), wheels can be created for packages like ``multidict``, ``discord.py``, and just about any other package that requires wheels to be made. It's important to note that by Python >= 3.8, you'll likely need to use the ``--no-use-pep517`` flag in order to skip PEP517 and assure success. 

This confirms the hypothesis that patched SDKs (such as those provided in [Okanon's SDK repository](https://github.com/okanon/iPhoneOS.sdk) or [theos/sdks](https://github.com/theos/sdks)) no longer work. There's no specific reason as to why this occurs, though it's likely a Python change or a failure in the SDKs provided by the repositories linked above. For now, this issue can be closed and settled, though I'd like to open it again in case the issue arises again in the future.

**Comment by lccambiaghi** [comment]
Hi @TheRealKeto I am trying to install Python packages in a virtual environment like you and I hit this issue. How can I get this SDK you are talking about? I would like to build Numpy/pandas.

**Comment by TheRealKeto** [comment]
Looking around, I can only find issues from Numpy pointing to this specific library, [OpenBLAS](https://github.com/xianyi/OpenBLAS), which Procursus currently doesn't provide. In reality, running any Python modules will not work on Procursus (or iOS in general) primarily because packages aren't built for iOS; they're just designed terribly.

This issue you've experienced specifically affects Numpy itself, which is out of the scope for this. Other packages might work, but that's not the case for Numpy. Sorry for the inconvenience. You might want to report an issue requesting support in [Numpy's Github page](https://github.com/numpy/numpy), but I doubt you might get far...
