### ISSUE TITLE
Please help me - I can't add this repo with Cydia

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [ProcursusTeam/Procursus#443]
![image](https://user-images.githubusercontent.com/45666011/109060413-ad2e1980-76e5-11eb-9503-32b627e1d53b.png)
![image](https://user-images.githubusercontent.com/45666011/109060379-9f789400-76e5-11eb-9287-09853da5616a.png)

**Comment by Diatrus** [comment]
You have to have Odyssey or Odysseyra1n (The Procursus bootstrap on checkra1n) to use Procursus. If you'd like to see Procursus on checkra1n or other jailbreaks, merely request them to add the option.
