### ISSUE TITLE
Issue with swift

### ISSUE THREAD

**Issue by demhademha** [ProcursusTeam/Procursus#46]
When using swift, and swift 5.3 and attempting to compile a swift file I get the following output 
<unknown>:0: error: unable to load standard library for target 'arm64-apple-ios12.0'
Cannot read termcap database;
using dumb terminal settings.
'cyclone' is not a recognized processor for this target (ignoring processor)
'+crypto' is not a recognized feature for this target (ignoring feature)
'+fp-armv8' is not a recognized feature for this target (ignoring feature)
'+neon' is not a recognized feature for this target (ignoring feature)
'+sha2' is not a recognized feature for this target (ignoring feature)
'+zcm' is not a recognized feature for this target (ignoring feature)
'+zcz' is not a recognized feature for this target (ignoring feature)
'cyclone' is not a recognized processor for this target (ignoring processor)

It seems that a library is missing. 

Device info:
Version: iOS 13.5
DeviceName: ipad 7th generation 
Jailbreak: odysseyra1n

**Comment by Diatrus** [comment]
You need to specify an sdk to use and your target as arm64-apple-ios13.4 or 13.5.

**Comment by demhademha** [comment]
Thanks
