### ISSUE TITLE
Can’t install certain items when on checkra1n

### ISSUE THREAD

**Issue by Doregon** [ProcursusTeam/Procursus#471]
The title. Procurses wants to replace ncurses with ncurses-term and ncurses-bin, and even if you change the dependencies in the .deb itself it still fails with “Unable to find symbol.” 

Tested on iPhone 5s, 12.5.1
Tested on iPhone 7, 13.3 + 14.5

**Comment by demhademha** [comment]
You have to have Odyssey or Odysseyra1n (The Procursus bootstrap on checkra1n) to use Procursus. If you'd like to see Procursus on checkra1n or other jailbreaks, merely request them to add the option.

**Comment by Doregon** [comment]
Ohhh okay, I must've overlooked that when I was searching around for different things. I took the following sentence on the README.md file and though that checkra1n, unc0ver, anything other than the ones you mentioned were supported:

> No jailbreak-specific software, meaning it is plug and play for anyone that decides to use it in their jailbreak or project.

Well okay, I'll see about asking for compatibility with other jailbreak types, thanks for letting me know that this is just how it was designed.

**Comment by mwoolweaver** [comment]
this part

> it is plug and play for anyone that decides to use it in their jailbreak or project.

It's not plug and play in the sense you can just swap out your current bootstrap for Procursus

**Comment by DaOfficialRolex** [comment]
Yeah unfortunately checkra1n natively supports the loading of other bootstraps. We are forced at least on the iOS side of things to use other jailbreak tools or use scripts before we load the default bootstrap in the checkra1n iOS app.
