### ISSUE TITLE
Issues with compiling on a Docker setup

### ISSUE THREAD

**Issue by ForceBru** [ProcursusTeam/Procursus#49]
Say, I build `wget` for the first time, right after cloning the repo. Everything goes smooth.

Now I try to build Rust:

```
bash-5.0# make rust
Makefile:66: Building for iOS
Makefile:104: Building on Linux
Makefile:298: Using ldid. Abort now and install ldid2 if this ldid does not support SHA256
bash: brew: command not found
bash: brew: command not found
Using previously built openssl.
mkdir -p \
	/Procursus/build_base/iphoneos-arm64/1600 /Procursus/build_base/iphoneos-arm64/1600/{System/Library/Frameworks,usr/{include/{bsm,os,sys,IOKit,libkern,mach/machine},lib}} \
	/Procursus/build_work/iphoneos-arm64/1600 /Procursus/build_stage/iphoneos-arm64/1600 /Procursus/build_dist/iphoneos-arm64/1600 /Procursus/build_strap/iphoneos-arm64/1600
git submodule update --init --recursive
wget -q -nc -P /Procursus/build_base/iphoneos-arm64/1600/usr/include \
	https://opensource.apple.com/source/xnu/xnu-6153.61.1/libsyscall/wrappers/spawn/spawn.h
wget -q -nc -P /Procursus/build_base/iphoneos-arm64/1600/usr/include/mach/machine \
	https://opensource.apple.com/source/xnu/xnu-6153.81.5/osfmk/mach/machine/thread_state.h
wget: can't open '/Procursus/build_base/iphoneos-arm64/1600/usr/include/mach/machine/thread_state.h': File exists
make: *** [Makefile:542: setup] Error 1
```

Or any other package, really. It attempts to execute `wget -q -nc -P /Procursus/build_base/iphoneos-arm64/1600/usr/include https://opensource.apple.com/source/xnu/xnu-6153.61.1/libsyscall/wrappers/spawn/spawn.h`and similar `wget` commands, but all these header files already exist, because I've already built some other package, so it now always fails.

The only quick way to solve this is to delete `/Procursus/build_base/iphoneos-arm64/1600/usr/include` and re-run `make rust`.

Same for files in `/Procursus/build_source`:

```
wget -q -nc -P /Procursus/build_source https://ftpmirror.gnu.org/libidn/libidn2-2.3.0.tar.gz{,.sig}
wget: can't open '/Procursus/build_source/libidn2-2.3.0.tar.gz': File exists
```

System:

    Linux f4077c4df32c 4.19.76-linuxkit #1 SMP Tue May 26 xx:xx:xx UTC 2020 x86_64 GNU/Linux

**Comment by Diatrus** [comment]
Please report information of specific software versions you're on, such as wget. Also, can I inquire why you cloned Procursus at /?

**Comment by ForceBru** [comment]
> Please report information of specific software versions you're on, such as wget. Also, can I inquire why you cloned Procursus at /?

```
# wget --version
GNU Wget 1.20.3 built on linux-musl.
```

Procursus is at `/` because I'm running this in a temporary Docker container, so it should be fine.

**Comment by Diatrus** [comment]
I agree, it should be fine. One thing of note is that those specific wget options, on any other os I've (or anyone else I know) have tested, pointedly prevent the existing filed from being redownloaded if it exists. If you would like, I can demonstrate on a Linux system of mine I have on hand.

**Comment by ForceBru** [comment]
Wait, but if I run `wget` outside the `Makefile`, there's no error:

```
bash-5.0# wget -q -nc -P /Procursus/build_source https://ftpmirror.gnu.org/libidn/libidn2-2.3.0.tar.gz{,.sig}
bash-5.0# wget -q -nc -P /Procursus/build_source https://ftpmirror.gnu.org/libidn/libidn2-2.3.0.tar.gz{,.sig}
bash-5.0# wget -q -nc -P /Procursus/build_source https://ftpmirror.gnu.org/libidn/libidn2-2.3.0.tar.gz{,.sig}
bash-5.0# echo $?
0
bash-5.0# ls /Procursus/build_source
libidn2-2.3.0.tar.gz      libidn2-2.3.0.tar.gz.sig
bash-5.0#
```

**Comment by Diatrus** [comment]
Yeah... That makes very little sense to me... If I could reproduce this on my own machine, I could be of more service, but I can't produce it on my Mac or Linux installation.

**Comment by ForceBru** [comment]
Turns out, I was using the wrong `wget` all along! I rebuilt everything and installed `wget` with `ask add wget` - and now there are no errors with it.

In other words, `GNU wget 1.20.3` from [my earlier comment](https://github.com/ProcursusTeam/Procursus/issues/49#issuecomment-653194405) _works_, but it wasn't used for some reason.
