### ISSUE TITLE
Compilation of curl on ubuntu

### ISSUE THREAD

**Issue by demhademha** [ProcursusTeam/Procursus#51]
Hi, when compiling curl on ubuntu I get the following error:
 
make curl
Makefile:66: Building for iOS
Makefile:104: Building on Linux
mkdir -p \
        /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600 /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/{System/Librar
y/Frameworks,usr/{include/{bsm,os,sys,IOKit,libkern,mach/machine},lib}} \
        /home/ahmed/downloads/Procursus/build_work/iphoneos-arm64/1600 /home/ahmed/downloads/Procursus/build_stage/iphoneos-arm64/1600 /home/ahmed/d
ownloads/Procursus/build_dist/iphoneos-arm64/1600 /home/ahmed/downloads/Procursus/build_strap/iphoneos-arm64/1600
git submodule update --init --recursive
wget -q -nc -P /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include \
        https://opensource.apple.com/source/xnu/xnu-6153.61.1/libsyscall/wrappers/spawn/spawn.h
wget -q -nc -P /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include/mach/machine \
        https://opensource.apple.com/source/xnu/xnu-6153.81.5/osfmk/mach/machine/thread_state.h
wget -q -nc -P /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include/bsm \
        https://opensource.apple.com/source/xnu/xnu-6153.81.5/bsd/bsm/audit_kevents.h
cp -af /home/ahmed/cctools/SDK/MacOSX.sdk/usr/include/{arpa,net,xpc} /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include
cp: cannot stat '/home/ahmed/cctools/SDK/MacOSX.sdk/usr/include/arpa': No such file or directory
cp: cannot stat '/home/ahmed/cctools/SDK/MacOSX.sdk/usr/include/net': No such file or directory
cp: cannot stat '/home/ahmed/cctools/SDK/MacOSX.sdk/usr/include/xpc': No such file or directory
make: *** [Makefile:545: setup] Error 1
ahmed@ahmed-T90B-Pro:~/downloads/Procursus$ 

Any help would be appreciated

**Comment by demhademha** [comment]
I have got the ios 11.2 sdk, and the Macosx 10.15 sdk.

**Comment by CRKatri** [comment]
You need to place a MacOS sdk called MacOSX.sdk at ~/cctools/SDK

- Cameron Katri

________________________________

**Comment by demhademha** [comment]
Hi, so moving my SDK worked, but what other framework am I missing? 

$ make curl
Makefile:66: Building for iOS
Makefile:104: Building on Linux
mkdir -p \
        /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600 /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/{System/Librar
y/Frameworks,usr/{include/{bsm,os,sys,IOKit,libkern,mach/machine},lib}} \
        /home/ahmed/downloads/Procursus/build_work/iphoneos-arm64/1600 /home/ahmed/downloads/Procursus/build_stage/iphoneos-arm64/1600 /home/ahmed/d
ownloads/Procursus/build_dist/iphoneos-arm64/1600 /home/ahmed/downloads/Procursus/build_strap/iphoneos-arm64/1600
git submodule update --init --recursive
wget -q -nc -P /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include \
        https://opensource.apple.com/source/xnu/xnu-6153.61.1/libsyscall/wrappers/spawn/spawn.h
wget -q -nc -P /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include/mach/machine \
        https://opensource.apple.com/source/xnu/xnu-6153.81.5/osfmk/mach/machine/thread_state.h
wget -q -nc -P /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include/bsm \
        https://opensource.apple.com/source/xnu/xnu-6153.81.5/bsd/bsm/audit_kevents.h
cp -af /home/ahmed/cctools/SDK/MacOSX.sdk/usr/include/{arpa,net,xpc} /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include
cp -af /home/ahmed/cctools/SDK/MacOSX.sdk/usr/include/libkern/OSTypes.h /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include/l
ibkern
cp -af /home/ahmed/cctools/SDK/MacOSX.sdk/usr/include/sys/{tty*,proc*,ptrace,kern*,random,vnode}.h /home/ahmed/downloads/Procursus/build_base/iphone
os-arm64/1600/usr/include/sys
cp -af /home/ahmed/cctools/SDK/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/* /home/ahmed/downloads/Procursus/build_base/iphoneos-ar
m64/1600/usr/include/IOKit
cp -af /home/ahmed/cctools/SDK/MacOSX.sdk/usr/include/{ar,launch,libproc,tzfile}.h /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/us
r/include
cp -af /home/ahmed/cctools/SDK/MacOSX.sdk/usr/include/mach/{*.defs,{mach_vm,shared_region}.h} /home/ahmed/downloads/Procursus/build_base/iphoneos-ar
m64/1600/usr/include/mach
cp -af /home/ahmed/cctools/SDK/MacOSX.sdk/usr/include/mach/machine/*.defs /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include
/mach/machine
cp -af /home/ahmed/downloads/Procursus/build_info/availability.h /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include/os
cp -af /home/ahmed/downloads/Procursus/build_info/IOKit.framework.iphoneos /home/ahmed/downloads/Procursus/build_base/iphoneos-arm64/1600/System/Lib
rary/Frameworks/IOKit.framework
cp: cannot stat '/home/ahmed/downloads/Procursus/build_info/IOKit.framework.iphoneos': No such file or directory
make: [Makefile:553: setup] Error 1 (ignored)
sed -E s/'__IOS_PROHIBITED|__TVOS_PROHIBITED|__WATCHOS_PROHIBITED'//g < /home/ahmed/cctools/SDK/iPhoneOS13.2.sdk/usr/include/stdlib.h > /home/ahmed/
downloads/Procursus/build_base/iphoneos-arm64/1600/usr/include/stdlib.h
bash: /home/ahmed/cctools/SDK/iPhoneOS13.2.sdk/usr/include/stdlib.h: No such file or directory
make: *** [Makefile:555: setup] Error 1

Again any help would be appreciated

**Comment by CRKatri** [comment]
Use a 13.2 sdk

- Cameron Katri

________________________________

**Comment by demhademha** [comment]
Can I use a 13.5 sdk?

**Comment by CRKatri** [comment]
If you do be sure to patch the main Makefile to use it

- Cameron Katri

________________________________

**Comment by demhademha** [comment]
Hi, which line of the main Makefile needs changing?
I really do appolagise for my questions 
Thank you very much

**Comment by CRKatri** [comment]
I’d recommend just using a 13.2 sdk, but line 105

- Cameron Katri

________________________________

**Comment by CRKatri** [comment]
https://github.com/okanon/iPhoneOS.sdk

- Cameron Katri

________________________________

**Comment by Diatrus** [comment]
You should always use the latest sdk possible. On Linux I will probably make it possible to set SYSROOT and MACOSX_SYSROOT.

**Comment by Diatrus** [comment]
Adding on to my previous comment: I just checked and it is possible to set both of those in your environment variables.

**Comment by demhademha** [comment]
Hi, I've successfully set everything up, would you like me to close the issue?

**Comment by Diatrus** [comment]
Sure

**Comment by demhademha** [comment]
Thanks for the support, will close now
