### ISSUE TITLE
Location of deb files on ubuntu

### ISSUE THREAD

**Issue by demhademha** [ProcursusTeam/Procursus#53]
Hi, so I typed "make curl package" and it was successful, but where's the default deb location?
I really do appolagise

**Comment by Diatrus** [comment]
`make curl-package` is the proper command. The package will be in build_dist.

**Comment by demhademha** [comment]
checking build system type... x86_64-pc-linux-gnu
checking host system type... aarch64-apple-darwin
checking target system type... aarch64-apple-darwin
checking how to print strings... printf
checking for aarch64-apple-darwin-gcc... aarch64-apple-darwin-clang
checking whether the C compiler works... no
configure: error: in `/home/ahmed/downloads/Procursus/build_work/iphoneos-arm64/1600/libgeneral':
configure: error: C compiler cannot create executables
See `config.log' for more details
I have both gcc, and g++ installed aswell as clang which it seems to have detected
Again, any help would be appreciated

**Comment by Diatrus** [comment]
No package is guaranteed to compile on Linux. I primarily test compiling on macOS. If one doesn't compile on Linux, feel free to fix it.
