### ISSUE TITLE
Package Request: Axel

### ISSUE THREAD

**Issue by Broadcastre** [ProcursusTeam/Procursus#542]
This is their repository: https://github.com/axel-download-accelerator/axel

If you could add this I would highly appreciate it.

Thanks

**Comment by demhademha** [comment]
Ok, I'm on it

**Comment by demhademha** [comment]
Axel has been added as of commit https://github.com/ProcursusTeam/Procursus/commit/cdfcd6517bc91beb18c0151b7218bd82aeb55f3f

**Comment by demhademha** [comment]
Axel is now available on the procursus repo
