### ISSUE TITLE
Fork of Procursus to run on other devices.

### ISSUE THREAD

**Issue by JoeMcRainbow** [ProcursusTeam/Procursus#547]
There are some really cool utilities and other stuff on Procursus, that I'm sure a lot of us would love to be able to use on jailbreaks where Procursus isn't the default bootstrap. I think it would be cool if there was an alt repo with system tools (ones that would break the ones in the original bootstrap) removed, leaving stuff like openjdk and pojavlauncher available for other jailbreaks.

**Comment by CRKatri** [comment]
A better solution would be to ask the developer of your jailbreak to switch over to Procursus.

**Comment by Diatrus** [comment]
> A better solution would be to ask the developer of your jailbreak to switch over to Procursus.

This would also be the easier solution.

Procursus is specifically structured and made to be self contained for reasons such as device security, package size footprint, and overall stability. It was designed from the ground up to be modular so any jailbreak can take advantage of it without even asking for my approval or assistance. If you want Procursus to be used on other jailbreaks, simply request the developer of said jailbreak to adopt it.

In the meantime, feel free to use a jailbreak that does currently use Procursus.

**Comment by badger200** [comment]
@Diatrus what about all of us on iOS 12.4 and 13.3 for which I’m not aware of any jailbreaks using procursus? I use unc0ver for everything after some horrible experiences straying elsewhere in the past. But I’m not against trying recommendations. 

I hate how unc0ver floods my dmesg with endless “library validation overrriden, executable is a platform binary but library is not.” And when I tweeted @Pwn2Ownd on Twitter he merely replied “Hmm none of my systems do that.” 🙄(Gee thanks. Well it happens on every single one of mine on every version of uncover the past 3 years spanning, even fresh/minimal installs, regardless of Substrate or Substitute.)

**Comment by Diatrus** [comment]
@badger200 Chimera and Odyssey both use procursus.
