### ISSUE TITLE
Package request: defaults

### ISSUE THREAD

**Issue by CRKatri** [ProcursusTeam/Procursus#562]
Having `defaults` on iOS without cephei would be great, I believe @quiprr was working on this at one point, but I'm not sure if that got finished.

**Comment by quiprr** [comment]
I abandoned this but will pick it back up this coming week.

**Comment by CRKatri** [comment]
Just wondering what the status is on this.

**Comment by quiprr** [comment]
Read/write functional, but nothing else from stock `defaults` (macOS-like) is complete. I'll throw it up in a Makefile this weekend, and update with new features when I get time.

**Comment by CRKatri** [comment]
Let me know when you publish what you do have

**Comment by quiprr** [comment]
[https://github.com/quiprr/defaults](defaults) - read/write for now. i'll throw in a Makefile sometime if no one else gets to it

**Comment by dlevi309** [comment]
@quiprr I just saw read through the repo, it’s pretty great! thanks for doing this!

**Comment by CRKatri** [comment]
I have finished https://github.com/ProcursusTeam/defaults, I will still have to add it to Procursus.
