### ISSUE TITLE
package requests

### ISSUE THREAD

**Issue by demhademha** [ProcursusTeam/Procursus#58]
hi, could you please add dock-xsl,  gcc po4a,, libtoolize, flex, cmake,  byson and pkg-config? 
thank you very much

**Comment by Diatrus** [comment]
Clang is already included, libtool includes libtoolize.

**Comment by absidue** [comment]
bison to be added in #76

**Comment by absidue** [comment]
cmake added in 23bb572

**Comment by Diatrus** [comment]
Might I ask why you need gcc rather than clang?

**Comment by demhademha** [comment]
Flex to be added in https://github.com/ProcursusTeam/Procursus/pull/153

**Comment by Diatrus** [comment]
Only things left here are po4a and docbook

**Comment by TheRealKeto** [comment]
``po4a`` has been added as part of #510, commit [``507688d``](https://github.com/ProcursusTeam/Procursus/commit/507688de46f4fc8f2e6c21250e65066b560507a7). Only thing left here is ``docbook-xsl``.

**Comment by Cryptiiiic** [comment]
docbook in progress #647

**Comment by m1stadev** [comment]
`docbook-xsl` added in aa1598a, completing the package requests.
