### ISSUE TITLE
Man pages for apt are not installed.

### ISSUE THREAD

**Issue by CRKatri** [ProcursusTeam/Procursus#59]
What happens:
```
mobile in ~ at iPhone118 
➜ man apt
No manual entry for apt
```
Although I expect it to show me the applicable man page for apt

**Comment by demhademha** [comment]
Does this also happen to you with git?

**Comment by CRKatri** [comment]
Git doesn’t have a man entry either.



- Cameron Katri
________________________________

**Comment by DiegoMagdaleno** [comment]
I guess you have an additional package that provides this, this is the way its done on Debian.

Other option is that the man pages are not in there, since they are hard to compile (personal experience) docbook is pain.

**Comment by CRKatri** [comment]
I believe it is the second option due to https://github.com/ProcursusTeam/Procursus/blob/master/apt.mk#L46

**Comment by DiegoMagdaleno** [comment]
Yeah it most likely it is that issue, a good fix for this would be to port Docbook XSL to procursus and have an option to build it with docs if desired.

Now the question is, does procursus supports multiple package configurations? Aka I want to build this with docs i want to build this without them.
