### ISSUE TITLE
Compile using system libraries.

### ISSUE THREAD

**Issue by CRKatri** [ProcursusTeam/Procursus#608]
This may be a fairly complicated thing to add, so it may be best to happen after the rewrite, but it would allow compiling a package and link against the libs in `/opt/procursus/lib`/`/usr/lib` as well as `BUILD_BASE/**/lib`, this would make compiling things much easier, as you wouldn't have to compile everything yourself, but can install the `libs` and headers from `apt.procurs.us` and speed up compiling packages from scratch cause you wouldn't have to compile every dep, just install them.

**Comment by Diatrus** [comment]
I can think on the logistics of this.

**Comment by CRKatri** [comment]
One of the main issues I see are validating that the package is installed, for example most packages that have `gettext` as a build dep only need `libintl`, figuring out for each `gettext` build dep that we need `libintl-dev` installed but not `libtextsytle-dev` could be quite tricky. But after that it's just a case of adding to `CFLAGS`, `LDFLAGS`, etc.

**Comment by CRKatri** [comment]
This is kind of accomplished using `build_tools/setup_base.sh` added in be585cb, I won't be doing anything else for this though.
