### ISSUE TITLE
APT: Patch adds GPL-3+ code to library, but rsh/nshttp methods are GPL-2 only

### ISSUE THREAD

**Issue by julian-klode** [ProcursusTeam/Procursus#638]
While looking over the APT patch, I noticed that you added several functions (strchrnul and memrchr) to apt-pkg that are licensed under the GPL-3 or later versions; but methods/rsh.cc and your nshttp method, which is derived from rsh, are GPL-2; which is incompatible with that.

I'd advise replacing the GPL-3'ed wrappers with ones from FreeBSD; I once had a branch for FreeBSD porting that had versions of those functions from FreeBSD, but I don't have it anymore.

**Comment by julian-klode** [comment]
I'll also try to figure out if we can relicense methods/rsh.cc to GPL-2+ like the rest (well most) of the code, because that one bit being that different is not helpful.

**Comment by Diatrus** [comment]
I can do this, but the only patches currently used actively are in place in the as2 branch. 👍 

The nshttp method is no longer being used, and has been replaced with the default implementation used in Debian.

**Comment by julian-klode** [comment]
Ah OK, I think you're OK then, as long as you don't ship the rsh binaries built from methods/rsh.cc, but you might want to double check.

**Comment by Diatrus** [comment]
This should be resolved as of commit f6a4b5fe83c46ca9869452f57d90934d6441f058. Thank you for the report!
