### ISSUE TITLE
Make package error

### ISSUE THREAD

**Issue by LaxusiC** [ProcursusTeam/Procursus#64]
Hello, I’m getting this issue

https://imgur.com/jOG3yIN

Make doesn’t make deb package when I build with theos. Make version from bingner work tho :/

**Comment by CRKatri** [comment]
Please put the output on pastebin, or paste it here, the image it too difficult to read

**Comment by 1Conan** [comment]
Not a Procursus issue. https://github.com/theos/theos/issues/478
