### ISSUE TITLE
dpkg -l

### ISSUE THREAD

**Issue by Mikasa-san** [ProcursusTeam/Procursus#69]
I get an error when I type “dpkg -l”

**Comment by Diatrus** [comment]
What error, because I don't

**Comment by Mikasa-san** [comment]
![](https://raw.githubusercontent.com/Mikasa-san/mikasa-san.github.io/master/85C1430E-6C8F-47B8-ABEC-FDD12DDD16F6.jpeg)

**Comment by Diatrus** [comment]
Install `less`.
