### ISSUE TITLE
`dscl` or `pw`

### ISSUE THREAD

**Issue by CRKatri** [ProcursusTeam/Procursus#727]
After spending way too much time on opensource.apple.com looking for `apfs/apfs_fsctl.h` (which I am still looking for if anyone knows where it is), I discovered that dscl is opensource at https://opensource.apple.com/source/DSTools/DSTools-162/ with I was unaware of, which is why I ported `pw`. But I am wondering if it would be better to port `dscl` instead is continuing to use `pw`, although iOS’ user system is very different from macOS iirc.

**Comment by Diatrus** [comment]
I, in no way shape or form, want the directory services shit on iOS even if it's possible.
