### ISSUE TITLE
tvOS support?

### ISSUE THREAD

**Issue by CodeyMoore** [ProcursusTeam/Procursus#828]
Would it be possible to add tvOS support to Procursus?

**Comment by TheRealKeto** [comment]
Procursus already has tvOS support; "we" simply do not distribute this architecture ourselves. [You can give this a try, if you want.](https://github.com/asdfugil/table/blob/master/README.TVOS.md)

**Comment by CodeyMoore** [comment]
Oh I didn’t even know that. 
how do I add it to my Apple TV?

**Comment by TheRealKeto** [comment]
I **literally** linked you the instructions...

**Comment by CodeyMoore** [comment]
I didn’t read the readme properly sorry

**Comment by CodeyMoore** [comment]
I’m still confused 😅

**Comment by TheRealKeto** [comment]
The instructions should be a lot more clear, since they've been updated.

**Comment by CodeyMoore** [comment]
I’ve been speaking with the developer in regards to help with it.

**Comment by Diatrus** [comment]
The build system already support tvOS.
