### ISSUE TITLE
Clang is unable to find dependencies

### ISSUE THREAD

**Issue by demhademha** [ProcursusTeam/Procursus#836]
Continuation of the previous issue with this name:

```
clang a.c -o a -L/usr/lib -lcurl 
ld: library not found for -lcurl
```
The libcurl development package is installed

**Comment by Diatrus** [comment]
Just tested, works a-ok.
![9031D86F-C28F-48F0-BF7B-6C5F96045D3E](https://user-images.githubusercontent.com/8144478/123335539-9c19db80-d512-11eb-8857-49cfe3ebae8d.jpeg)

**Comment by demhademha** [comment]
Do you have any idea on what could be the issue?
I'm on clang-11 btw

**Comment by Diatrus** [comment]
No idea. Just apt upgrade and make sure you haven't set SDKROOT, and you should be fine.
