### ISSUE TITLE
coreutils and darwintools

### ISSUE THREAD

**Issue by kaloody99** [ProcursusTeam/Procursus#848]
Hello,

I am facing a problem with these tweaks coreutils and darwintools that I can't install with new updates. I uploaded pic to explain my problem I have. My device is iPhone 6 Plus iOS 12.5.4

![image](https://user-images.githubusercontent.com/48293343/123523842-7c122580-d694-11eb-9c2a-b789d0b5375f.jpeg)

**Comment by TheRealKeto** [comment]
This is a known issue affecting iOS 12 and 13 users; we're working on it.

**Comment by Diatrus** [comment]
It’s not a known issue lol, it was fixed yesterday.

**Comment by kaloody99** [comment]
> It’s not a known issue lol, it was fixed yesterday.

I never tried again until now. Thanks a lot.
