### ISSUE TITLE
[Idea] Easier maintenance of .deb packages

### ISSUE THREAD

**Issue by hwittenborn** [ProcursusTeam/Procursus#881]
I've got a project [I'm currently working on](https://github.com/hwittenborn/makedeb) that, if builds are done on Linux systems, might make packages here easier to manage.

It would all be done in the [PKGBUILD format](https://wiki.archlinux.org/title/PKGBUILD), where you could include all the details about a package inside of a single file, including the steps to download sources as well as commands to build the program. You can see an example of how you would set one up [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=makedeb) and [here](https://wiki.archlinux.org/title/Arch_package_guidelines#PKGBUILD_prototype).

makedeb (the very first link at the top) could also probably be ported to iOS if needed, as the majority of its functionality is just inside of Bash scripts.

Not sure if it would be feasible to implement, or even how much benefit it would provide, but I though I'd just throw it out there.

**Comment by Diatrus** [comment]
One of our contributors actually already did something similar. https://github.com/CRKatri/BBS
It wouldn't provide much benefit over how it's already done + how it's planned to be improved.
