### ISSUE TITLE
Network interface error with aircrack-my

### ISSUE THREAD

**Issue by cloud3799** [ProcursusTeam/Procursus#902]
what network interface is supposed to be used with aircrack-ng. i'm using an iPhone 8 which I believe uses broadcom BCM4361 chip. Whenever I try "airodump-ng en0" it says failed to use network interface.

**Comment by Diatrus** [comment]
The behavior is the same on macOS actually. Don't believe this would be a Pro issue, more of an upstream issue.

**Comment by Diatrus** [comment]
See here: http://www.aircrack-ng.org/doku.php?id=faq#is_mac_os_x_supported
