### ISSUE TITLE
fish dependency

### ISSUE THREAD

**Issue by theotheroracle** [ProcursusTeam/Procursus#938]
fish depends on awk for autocompletion, and gives errors constantly when it's not installed . 

there's another issue with makewhatis, but i don't think that can be resolved here, i made a corresponding issue on the fish repo
https://github.com/fish-shell/fish-shell/issues/8205 EDIT: this part will be fixed upstream

**Comment by Diatrus** [comment]
Thanks for the report. We can have that first issue resolved quickly, I believe.

**Comment by demhademha** [comment]
Issue two has been fixed upstream

**Comment by CRKatri** [comment]
Closed by ce9e38a
